name: Deploy to ACI

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build and push container image
      uses: azure/docker-login@v1
      with:
        login-server: kyroregistry.azurecr.io
        username: kyroregistry
        password: Zjh9RuiimRmVKGc+g+Vtn3H0WcfZzxkG8ouIHvEowh+ACRDbhaPB

    - name: Build and push container image
      run: |
        docker build -t mycontainer .
        docker tag mycontainer kyroregistry.azurecr.io/mycontainer:${{ github.sha }}
        docker push kyroregistry.azurecr.io/mycontainer:${{ github.sha }}

    - name: Create Azure resources
      uses: azure/cli@v1
      with:
        azcliversion: latest
        inlineScript: |
          az login --service-principal -u 7176f740-9303-4d46-b1aa-957ebedf94b5 -p lhL8Q~AV-aARu9t.EHN4uatKkuEQr.Bb9npQvcc1 --tenant 9fa97d99-5744-4766-89bc-f560b9a21102
          az group create --name kyro-rg --location eastus
          az cosmosdb create --name kyrocosmosbd --resource-group  kyro-rg --kind GlobalDocumentDB
          az container create --name containerkyro --resource-group  kyro-rg --image kyroregistry.azurecr.io/containerkyro:${{ github.sha }} --ip-address public --ports 80 --environment-variables COSMOSDB_URI=https://kyrocosmosbd.documents.azure.com:443/ COSMOSDB_KEY=PhiyQ75Cb2G0AY4EuhCjNWlabQtylLN1NxhfpXu5eGlw3nZ0Ya8Ga0PjnTJR1V6C028h5ehF9amiACDbqbV6Rg==

    - name: Connect to Cosmos DB
      uses: azure/cosmosdb-action@v1
      with:
        cosmos-db-account: https://kyrocosmosbd.documents.azure.com:443/
        cosmos-db-key: PhiyQ75Cb2G0AY4EuhCjNWlabQtylLN1NxhfpXu5eGlw3nZ0Ya8Ga0PjnTJR1V6C028h5ehF9amiACDbqbV6Rg==
        database-name:kyrocosmosbd
        collection-name: containerkyro
